### ISSUE TITLE
[bug] Подсветка редактирования поста остается белой

### ISSUE THREAD

**Issue by viktor02** [Dmitiry1921/VK-Dark#1]
Скрипт замечателен, но заметил один баг: происходит он, когда пост публикуется и появляется в ленте, но замечал его только с сообществом Хабра(возможно, пост при появлении сразу редактируется, и из-за этого такой эффект)

![00290](https://user-images.githubusercontent.com/19672960/84117034-92bdee00-aa39-11ea-92c3-e8beb79822d0.png)

**Comment by Dmitiry1921** [comment]
Спасибо за помощь в развитии проекта @viktor02  обязательно исправлю в следующем обновлении.

**Comment by Dmitiry1921** [comment]
@viktor02  ты можешь присоеденится в чат и оперативно сообщать и найденых ошибках, будем рады видеть: https://vk.me/join/AJQ1d7U5CANH4MRXOBNPuzB4
