### ISSUE TITLE
[bug] Оповещение о дне рождения остается белым

### ISSUE THREAD

**Issue by viktor02** [Dmitiry1921/VK-Dark#2]
![изображение](https://user-images.githubusercontent.com/19672960/84136436-f9e89c00-aa53-11ea-95f0-45a0f560ecda.png)

**Comment by Dmitiry1921** [comment]
Спасибо поправлю в ближайшем релизе @viktor02

**Comment by Dmitiry1921** [comment]
@viktor02 еще актуально не знаешь ?

**Comment by viktor02** [comment]
А вот не знаю, проверю в ближайшие дни :)

**Comment by viktor02** [comment]
![изображение](https://user-images.githubusercontent.com/19672960/129674224-b1932e71-5959-4ceb-a49e-f660e6c3cce8.png)
Да, все нормально.
